//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materials.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buildings
    {
        public Buildings()
        {
            this.Customers = new HashSet<Customers>();
        }
    
        public int PKBuilding { get; set; }
        public string Building { get; set; }
    
        public virtual ICollection<Customers> Customers { get; set; }
    }
}
