//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materials.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.PartNumbers = new HashSet<PartNumbers>();
        }
    
        public int PKCustomers { get; set; }
        public string Customer { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> FKBuilding { get; set; }
    
        public virtual Buildings Buildings { get; set; }
        public virtual ICollection<PartNumbers> PartNumbers { get; set; }
    }
}
