//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materials.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartNumbers
    {
        public int PKPartNumber { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> FKCustomer { get; set; }
        public bool Available { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
